# -*- coding: utf-8 -*-
"""Bagging.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sr0JgGH_wfxXShd5bh8PTrQzHt6mK_95
"""

#Impor Library 
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import make_pipeline
from sklearn.ensemble import BaggingClassifier
from sklearn.model_selection import GridSearchCV


#Load cancer dataset
bc = datasets.load_breast_cancer()
X = bc.data
y = bc.target


#membagi dataset 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=1, stratify=y)


#Melakukan pipelining 
pipeline = make_pipeline(StandardScaler(),
                        LogisticRegression(random_state=1))
	

#Skema bagging
bgclassifier = BaggingClassifier(base_estimator=pipeline, n_estimators=100,
                                 max_features=8,
                                 max_samples=80,
                                 random_state=1, n_jobs=5)

bgclassifier.fit(X_train, y_train)

print('Model test Score: %.3f, ' %bgclassifier.score(X_test, y_test),
      'Model training Score: %.3f' %bgclassifier.score(X_train, y_train))