# -*- coding: utf-8 -*-
"""CART.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10kbxV8Q7WaRV-WhNRqqgGt7uh3O2N8GU
"""

# Load Dataset
import numpy as np
import matplotlib.pyplot as plt 
import pandas as pd  

from sklearn.datasets import load_boston
boston_dataset = load_boston()

boston = pd.DataFrame(boston_dataset.data, columns=boston_dataset.feature_names)

boston['MEDV'] = boston_dataset.target
names = boston_dataset.feature_names


#Library CART pada python
from sklearn.tree import DecisionTreeRegressor 

array = boston.values

X = array[:,0:13]
Y = array[:,13]
#print(X)
#print(Y)

from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=1234)


#model = DecisionTreeRegressor(max_leaf_nodes = 20)

model = DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
           max_leaf_nodes=50, min_impurity_decrease=0.0,
  
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           random_state=None, splitter='best')

#Evaluasi 
rt = model.fit(X_train, Y_train)
rt

import random as rnd

rnd.seed(123458)
X_new = X[rnd.randrange(X.shape[0])]
X_new = X_new.reshape(1,13)

#Prediksi Model 
YHat = model.predict(X_new)


df = pd.DataFrame(X_new, columns = names)
df["Predicted Price"] = YHat
df.head(1)

from sklearn.metrics import r2_score
YHat = model.predict(X_test)
print(YHat)

#Menghitung Rata-rata Kuadrat
r2 = r2_score(Y_test, YHat)
print("R-Squared = ", r2)

from sklearn.tree import plot_tree

plt.figure()
clf = DecisionTreeRegressor().fit(X_test, Y_test)
plot_tree(clf, filled=True)
plt.title("Decision tree X, Y Test Load Boston")
plt.show()