# -*- coding: utf-8 -*-
"""Tanpa_Bagging.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kz9GcW0AJRGkplL0UnM7qRlQtRhowGMC
"""

#Impor Library 
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import make_pipeline
from sklearn.ensemble import BaggingClassifier
from sklearn.model_selection import GridSearchCV


#Load cancer dataset
bc = datasets.load_breast_cancer()
X = bc.data
y = bc.target


#membagi dataset 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=1, stratify=y)
	
logreg =  LogisticRegression(solver='liblinear') 

# fit the model with data 

logreg.fit(X_train,y_train) 

# predicting 

y_pred=logreg.predict(X_test) 

y_pred

import matplotlib.pyplot as plt

from sklearn import metrics

print("Accuracy:",metrics.accuracy_score(y_test, y_pred)) 

print("Precision:",metrics.precision_score(y_test, y_pred)) 

print("Recall:",metrics.recall_score(y_test, y_pred))